### ISSUE TITLE
Name on Form

### ISSUE THREAD

**Issue by aschlue** [OvilleTown/CovidAssessmentsIssues#3]
![Covid Assessment](https://user-images.githubusercontent.com/71328689/99554873-ae84d300-298d-11eb-8897-dc80c4a920e3.PNG)

I logged in with my personal email and it won't let me enter my first and last name in the form, it's grayed out

**Comment by OvilleTown** [comment]
The first and last name should be pulling from the profile that was set up.  This was not saving correctly, it has been fixed now.
