### ISSUE TITLE
Link did not work for Andrea and i this morning when i tried to do a demo

### ISSUE THREAD

**Issue by cathymoran** [OvilleTown/CovidAssessmentsIssues#6]
Also - we decided to just go with employees for now
When the employee answers 'yes' to a question - the end result page should say ' Do not enter the workplace. Please complete the online Public Health self-assessment here( link)  and follow instructions. Contact your supervisor or manager.'
The 'yes' questionnaires can go to HR Inbox.

**Comment by OvilleTown** [comment]
part about results page a duplicate of #5.

**Comment by OvilleTown** [comment]
The link requires VPN to work, as well it requires https in the testing environment making it https://assessments.orangeville.ca
